### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by chritchens** [project-everest/hacl-star#138]
Hi everyone!

I was curious about the project and I've tried to verify and test it on my laptop, which runs a simple 64 bit Ubuntu 18.04. After running `make test-all`, I've stumbled into an error:

"libhacl32.so: could not read symbols: File in wrong format"

Reading on the Makefile, it has to do with keeping linux OSes in pair with windows, where you cannot test both the 64 bit and 32 bit version. So I guess the issue may have to do with https://github.com/project-everest/hacl-star/issues/14.

If it's not the case, are there particular notes on how to properly run tests? Maybe I've just missed some details or some passages.

All the bests

**Comment by msprotz** [comment]
Hello,

I assume that you're running tests on the master branch. It has been frozen for quite some time, and your issue is unlikely to be fixed there.

If you have the time and motivation, and depending on what you're trying to achieve, you could switch to:
- F*'s master branch
- KReMLin's master branch
- hacl-star's fstar-master branch, which tracks upstream F* master (hence the name)
There, the "make test" target will run a series of tests that are I think comparable to what is on HACL* master. The packaging is somewhat improved, and all the HACL* files will be gathered in the `dist/compact` directory. Along with the contents of `kremlin/kremlib/dist/minimal`, this is all you need to use HACL*.

Let us know what you're trying to achieve and hopefully we can help a little more.

Cheers,

Jonathan

**Comment by Basse333** [comment]
No switching, you need to instal a program and youse a windows computer, No Apple or linux
________________________________
Från: Jonathan Protzenko <notifications@github.com>
Skickat: den 23 januari 2019 05:15:12
Till: project-everest/hacl-star
Kopia: Basse333; Comment
Ämne: Re: [project-everest/hacl-star] Tests failing (#138)


Hello,

I assume that you're running tests on the master branch. It has been frozen for quite some time, and your issue is unlikely to be fixed there.

If you have the time and motivation, and depending on what you're trying to achieve, you could switch to:

  *   F*'s master branch
  *   KReMLin's master branch
  *   hacl-star's fstar-master branch, which tracks upstream F* master (hence the name)
There, the "make test" target will run a series of tests that are I think comparable to what is on HACL* master. The packaging is somewhat improved, and all the HACL* files will be gathered in the dist/compact directory. Along with the contents of kremlin/kremlib/dist/minimal, this is all you need to use HACL*.

Let us know what you're trying to achieve and hopefully we can help a little more.

Cheers,

Jonathan

**Comment by s-zanella** [comment]
@Basse333 Could you please refrain from posting misleading answers? I deleted your previous comment where you suggested that you were an owner of the repository. We will have no other option but to block you and report your comments as abuse if you persist.

@msprotz answer is accurate and to the point.

**Comment by chritchens** [comment]
@msprotz, @s-zanella, thank you very much! I'll try as soon as possible.

Cheers

**Comment by Basse333** [comment]
Why should you block me?
________________________________
Från: Santiago Zanella-Beguelin <notifications@github.com>
Skickat: den 23 januari 2019 15:25:16
Till: project-everest/hacl-star
Kopia: Basse333; Mention
Ämne: Re: [project-everest/hacl-star] Tests failing (#138)


@Basse333<https://github.com/Basse333> Could you please refrain from posting misleading answers? I deleted your previous comment where you suggested that you were an owner of the repository. We will have no other option but to block you and report your comments as abuse if you persist.

@msprotz<https://github.com/msprotz> answer is accurate and to the point.

**Comment by s-zanella** [comment]
@Basse333 You first lied and pretended to be an owner of the repository, then derailed the conversation with an inaccurate answer. You are making it hard to believe that your comments are well-meaning.

**Comment by chritchens** [comment]
Updates. I've followed @msprotz suggestions and the `make all` on hacl-star fails with this message:

`Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error. Unix.Unix_error(Unix.ENOMEM, "fork", "")
Makefile:75: recipe for target /.../hacl-star/code/tests/Hacl.Test.SHA3.fst.checked' failed`

I had already built fstar from source, and so kremlin. They were behind some commits though. The branch is fstar-master, the commit 6d8287e2bac7f1811aeefa472e959ed27131d01c.

On @Basse333, I think it could be a good idea for your project to have some clear code of conduct. I'm not a big fun of overly complex CoC, nor per se formal ones, but if s/he has stated falsely something like being the owner of this repository, I think you should make some move and automate in future cases.

Anyway, great project, congrats!

All the bests

**Comment by msprotz** [comment]
Looks like you're on the right track and your build just failed because you ran out of memory. I would run `make` again with a smaller parallel factor (the build is fairly parallel).

Note that there is currently a limitation wherein a sub-component of the build has a hardcoded -j factor which you might want to decrease manually (see vale/Makefile).

Thanks,

Jonathan

**Comment by chritchens** [comment]
My bad, I've reported `make` without `-jN`, but I usually use any `make` command with `-jN`. In this case it was `-j8`. I will try to increase it just in case.

Bests,
Christian

**Comment by chritchens** [comment]
Build done, test passed after installing `scons`.

I've noticed that both the build and test process have been greatly improved, congrats, that's quite cool!

Thank you for the help @msprotz and @s-zanella!
