### ISSUE TITLE
Failure to resolve implicit argument

### ISSUE THREAD

**Issue by newuser1212** [project-everest/hacl-star#167]
The below code in ```Test2impl``` is failing with Failed to resolve implicit argument ?55 of type Lib.IntTypes.size_t introduced for Instantiating implicit argument in application but I can't seem to figure out how to resolve it. It seems to be the modification to the buffer before it goes through the repeat function, which uses ```as_seq h0 b```.

```Test2spec.fst```

```FStar
module Test2spec

open Lib.IntTypes
open Lib.Sequence
open FStar.Mul
open Lib.LoopCombinators

let test2 (a:lseq uint64 5) (x:nat{x<5 }) (b:lseq uint64 5) : Tot (lseq uint64 5) = 
 b.[x] <- a.[x]
 
let test2_repeat (a:lseq uint64 5) (b:lseq uint64 5) : Tot (lseq uint64 5) =
 let b = b.[0] <- b.[1] in //I think this is the line that causes the error
  repeati 5 (test2 a) b
```
```Test2impl.fst```

```FStar
module Test2impl

open FStar.HyperStack.All
open FStar.HyperStack
open FStar.HyperStack.ST
open FStar.Mul
open LowStar.Buffer
open LowStar.BufferOps
open Lib.IntTypes
open Lib.Buffer
module ST = FStar.HyperStack.ST
module Loop = Lib.LoopCombinators
module S = Test2spec

val test2:
  a:lbuffer uint64 5ul
  -> x:uint_t U32 PUB {v x<5}  
 -> b:lbuffer uint64 5ul 
  -> Stack unit
    (requires fun h -> live h a /\ live h b /\ disjoint a b)
    (ensures fun h0 r h1 -> 
      modifies (loc b) h0 h1 /\
            as_seq h1 b == S.test2 (as_seq h0 a) (v x) (as_seq h0 b))      
  
let test2 a x b =
  b.(x) ← a.(x)

val test2_repeat:
  a:lbuffer uint64 5ul
  -> b:lbuffer uint64 5ul
  -> Stack unit
    (requires fun h -> live h a /\ live h b /\ disjoint a b)
    (ensures fun h0 r h1 -> 
      modifies (loc b) h0 h1 /\ 
      as_seq h1 b == S.test2 (as_seq h0 a) (as_seq h0 b))
 
let test2_repeat a b =
 let b = b.(0ul) <- b.(1ul) in	
  [@ inline_let]
 let spec h0 = S.test2 (as_seq h0 a) in
 let h0 = ST.get() in 
 loop1 (h0) (5ul) (b) (spec)
  (fun x -> 
    Loop.unfold_repeati 5 (spec h0) (as_seq h0 b) (v x);   
    test2 a x b
  )
```

**Comment by s-zanella** [comment]
Some general remarks:

- No need to add `Tot` annotations (unless you need a `decreases` clause, for syntactic reasons).`Tot` is the default effect.
- No need to open `FStar.HyperStack.All` unless you plan to use the `All` or `ML` effects.
- No need to open `LowStar.Buffer` or `LowStar.BufferOps`. In fact, opening `Lib.Buffer` after them is shadowing many of the definitions in these namespaces.
- No need to open `FStar.Mul` in this particular example since you aren't using the `*` operator.
- It's more idiomatic to use `modifies1 b h0 h1` than `modifies (loc b) h0 h1`.
- This in `test2` is dead code ` b.(size 0) <- b.(size 1)` since you're later overwriting `b.(size 0)`. In fact, all this function does is copying `a` into `b` and you could have used `Lib.Buffer.copy` instead.
- The type of `test2_repeat` doesn't even lax-typecheck because of this expression `as_seq h1 b == S.test2 (as_seq h0 a) (as_seq h0 b)`. I assume you meant `S.test2_repeat`

**Why the `Failed to resolve implicit argument` error?**

In the code of `test2_repeat` you're unnecessarily let-binding the result of updating `b.(0ul)`, and you're using `b`! From that point on `b` has type `unit` and the rest of the code is ill-typed. Because implicit parameter resolution happens before F* can realize this, the error tells you that it couldn't infer the value of the implicit `size_t` parameter of `Lib.Sequence.as_seq`. This parameter is the length of the buffer and it doesn't have this information since `b` is not even a buffer.

- Here's how I would have written this in a single file, fixing the errors above:

```FStar
module M

open FStar.HyperStack.ST

open Lib.IntTypes
open Lib.Sequence
open Lib.Buffer

module ST = FStar.HyperStack.ST
module Loop = Lib.LoopCombinators

let f_spec (a:lseq uint64 5) (x:nat{x < 5}) (b:lseq uint64 5) : lseq uint64 5 = 
  b.[x] <- a.[x]

let f_repeat_spec (a:lseq uint64 5) (b:lseq uint64 5) : lseq uint64 5 =
  let b = b.[0] <- b.[1] in
  Loop.repeati 5 (f_spec a) b

val f:
    a:lbuffer uint64 (size 5)
  -> x:uint_t U32 PUB {v x < 5}  
  -> b:lbuffer uint64 (size 5) 
  -> Stack unit
    (requires fun h -> live h a /\ live h b /\ disjoint a b)
    (ensures  fun h0 r h1 -> 
      modifies1 b h0 h1 /\
      as_seq h1 b == f_spec (as_seq h0 a) (v x) (as_seq h0 b))
let f a x b =
  b.(x) ← a.(x)

val f_repeat:
    a:lbuffer uint64 (size 5)
  -> b:lbuffer uint64 (size 5)
  -> Stack unit
    (requires fun h -> live h a /\ live h b /\ disjoint a b)
    (ensures  fun h0 r h1 -> 
      modifies1 b h0 h1 /\ 
      as_seq h1 b == f_repeat_spec (as_seq h0 a) (as_seq h0 b))
let f_repeat a b =
  b.(size 0) <- b.(size 1);
  [@ inline_let]
  let spec h0 = f_spec (as_seq h0 a) in
  let h0 = ST.get () in 
  loop1 h0 (size 5) b spec
    (fun x -> 
      Loop.unfold_repeati 5 (spec h0) (as_seq h0 b) (v x);         
      f a x b
    )
```
