### ISSUE TITLE
Expected a Ghost Expression

### ISSUE THREAD

**Issue by Jazperson2** [project-everest/hacl-star#177]
I want to define a buffer that ensures its objects inside do not exceed, in this case signed integers that do not exceed the maximum range. The code below came back with a  ```(Error 58) Expected a ghost expression; got an expression "let _ = ...``` 

```FStar
open FStar.HyperStack.All
open FStar.HyperStack
open FStar.HyperStack.ST
open Lib.IntTypes
open Lib.Buffer

val exp:
	buffer1: (lbuffer int64 3ul) {forall (index:size_t{v index<3}). (v buffer1.(index) + v buffer1.(index) < maxint S64)}
//forall (index:nat{index<3}). range(v buffer1.(index) + v buffer1.(index))(Lib.IntTypes.S64)
	-> Stack unit
	(requires fun h -> live h buffer1)
	(ensures fun h0 r h1 ->True)
```

**Comment by s-zanella** [comment]
`b.(i)` expands to `Lib.Buffer.index` that has `Stack` effect. All expressions in refinements (assertions, pre-conditions, etc.) need to be `Ghost`. 
You can use `Seq.index (as_seq h b) (v i)` instead of `b.(i)` in the `requires` clause. Obviously, you can't use this in the refinement of `buffer1` because you don't have access to a initial heap.
