### ISSUE TITLE
Hacl_Standalone_Poly1305_64_crypto_onetimeauth stack overflow?

### ISSUE THREAD

**Issue by guidovranken** [project-everest/hacl-star#185]
I was just browsing the source code (haven't tested this) and I think that because ```Hacl_Standalone_Poly1305_64_poly1305_blocks``` is recursive, it can lead to a stack overflow through ```Hacl_Poly1305_64_crypto_onetimeauth``` for a sufficiently large value of ```len1``` (or a sufficiently small stack)?

**Comment by prosecco** [comment]
I assume you are looking  at the code in the master branch?
We have since evolved the code away from using recursion, so if you want to use this code drop us an email and we can send you an updated version.

Coming back to your question, this function is tail-recursive, so with any modern C compiler with optimization level “-O2” or above this recursion is eliminated,
so no extra stack is consumed and you will not see a stack overflow. However, if you use a lower optimization level, you may indeed run out of stack for some values
of “len1”.

-Karthik

**Comment by guidovranken** [comment]
> I assume you are looking at the code in the master branch?

I found this initially in Mozilla NSS (trunk).

> Coming back to your question, this function is tail-recursive, so with any modern C compiler with optimization level “-O2” or above this recursion is eliminated, so no extra stack is consumed and you will not see a stack overflow. However, if you use a lower optimization level, you may indeed run out of stack for some values of “len1”.

I don't think that's necessarily through. My experience with clang has been that it does some unrolling with -O2/-O3 but the actual recursion is still there.

Anyway, I'm not a user of this software directly myself, I just wanted to notify you, so I'm closing this issue now.

**Comment by s-zanella** [comment]
See also https://github.com/project-everest/hacl-star/issues/39 and https://github.com/mitls/mitls-papers/issues/38 for exhaustive lists of recursive functions in Hacl* and miTLS (at the time of posting).

At this moment, in the main development branches `fstar-master` and `dev`, I believe the only recursive functions remaining are in library for Merkle trees and `EverCrypt_HKDF_hkdf_expand_loop`, which should be rewritten as a loop.
