### ISSUE TITLE
AVX(2) feature detection does not check for OS support

### ISSUE THREAD

**Issue by sopium** [project-everest/hacl-star#315]
(For context, I was trying to build a Rust binding for the C/ASM code in `dist` from master, and noticed some problems.)

When you detect AVX(2) support, you need to check for OS support too. When the CPU supports AVX(2) but the OS does not, you cannot use the AVX(2) version.

You can disable AVX(2) support on linux with the `noxsave` boot option to test this: a program that uses e.g. `EverCrypt_Chacha20Poly1305_aead_encrypt` will crash with `SIGILL`. (On a CPU with AVX2 support, and after first calling `EverCrypt_AutoConfig2_init`, of course.)

See also this gcc bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85100

**Comment by msprotz** [comment]
Thanks that's very helpful. I was absolutely not aware of that.

- @sopium: can other flags be similarly disabled (e.g. ADX, BMI2, etc.) or is it only AVX that may or may not be enabled?
- @R1kM or @Chris-Hawblitzel: how feasible is it to replicate the behavior of https://gcc.gnu.org/bugzilla/attachment.cgi?id=43793&action=diff in our CPU detection routines?

**Comment by sopium** [comment]
> Thanks that's very helpful. I was absolutely not aware of that.
> 
>     * @sopium: can other flags be similarly disabled (e.g. ADX, BMI2, etc.) or is it only AVX that may or may not be enabled?

I think it's just AVX (and AVX2, AVX512).

**Comment by msprotz** [comment]
@R1kM and I spent a long while looking at this today, and it's a lot more complicated than we thought. This bug report from OpenSSL contains some good information: https://rt.openssl.org/Ticket/Display.html?id=2633&user=guest&pass=guest

Here's our understanding so far. In order to successfully use XMM, YMM or ZMM registers, the OS must support restoring the state of these registers upon context-switching. There appears to be two ways to do this, one dubbed OSXSAVE and the other dubbed XSAVE. (We have the property that `OSXSAVE` implies `XSAVE`.) Furthermore, after ascertaining that extended register support saving is enabled, we must check that it is enabled *for the specific kind of register we intend to use* (xmm and ymm for AVX/AVX2, zmm for AVX512).

This means that before even checking for the presence of the AVX, AVX2 or AVX512 instruction set, we must check that support for these saving and restoring those registers has been enabled. Support for OSXSAVE or XSAVE is advertised via bits 26 and 27 of ecx as returned by CPUID. (Note: the case where AVX instructions are available but the OS won't save these registers apparently happens in virtualization situations, per the OpenSSL ticket.) Support for saving individual classes of registers is exposed via the XGETBV instruction.

From what I gather from the OpenSSL discussion, XSAVE is a somewhat older way to save extended registers and almost all OSes, if they do so, now use OSXSAVE to save and restore those registers. The GCC patch is thus conservative and may miss out some legacy or corner cases where it would've been ok to use AVX instructions when the XSAVE feature is used.

I propose we essentially follow GCC and keep things simple.
- A new Vale function exposed via interop returns the value of the OSXSAVE bit, without any deep semantics.
- A new Vale function, exposed via interop as well, returns the two 64-bit integers return by XSETBV, also without any deep semantics.
- An (unverified) logic does the exact same bit-masking and boolean setting as GCC does.

For reference, the final GCC patch is here: https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=7c05c7f7c39a01d91e4e0112fcff43f29a2110a3;hp=ad96bffb19f077b01343dd2f1a4df0511c67c414

I'm still puzzled by some elements of GCC's patch logic:
- are there vicious cases where YMM registers are present, OSXSAVE is enabled, but not for those specific registers? that seems insane
- is there no ordering between the XSTATE bits? if XSTATE_HI_ZMM is enabled, then surely all the sub-pseudo registers for XMM and YMM must be saved too, meaning that XSTATE_ZMM, XSTATE_YMM and XSTATE_SSE are all true?

But, seeing that none of us has the expertise and time to dig into this any further, I suggest we stick with what GCC is doing unless someone has a better insight.
