### ISSUE TITLE
heap free support gone?

### ISSUE THREAD

**Issue by aep** [project-everest/hacl-star#326]
trying to updating from an old hacl checkout, i noticed some apis now require heap.

for example there's no way to allocate memory for sha256 except Hacl_Streaming_SHA2_256_create_in which requires malloc.

is this intentional or am i using the wrong api to update?

**Comment by msprotz** [comment]
Based on your usage of underscores, I'm assuming you're calling these functions from C?

Looking at https://github.com/project-everest/hacl-star/blob/master/dist/gcc-compatible/Hacl_Hash.h you still have the error-prone, block-based API:
- Hacl_Hash_Core_SHA2_init_256
- Hacl_Hash_SHA2_update_multi_256
- Hacl_Hash_SHA2_update_last_256
- Hacl_Hash_Core_SHA2_finish_256

This requires you to follow this exact sequence of calls and make sure the argument of update_multi is a multiple of the block size.

(Of course there's still the one-shot API in this file which is safe, but based on your bug report I suspect you don't have all of the data available at once.)

https://github.com/project-everest/hacl-star/blob/master/dist/gcc-compatible/Hacl_Streaming_SHA2_256.h is a much safer API that does the internal buffering for you so that you can pass arbitrary amounts of data, and has no such strict state machine; can you say a little bit more about your use-case and why you can't use malloc()?

**Comment by aep** [comment]
> I'm assuming you're calling these functions from C?

yes

> Looking at https://github.com/project-everest/hacl-star/blob/master/dist/gcc-compatible/Hacl_Hash.h

aah thats where they went, thanks! Are those going to stay? I'm fine with the unsafe API.

>  why you can't use malloc()?

we're using hacl-star in [carrier](https://github.com/devguardio/carrier) which works on systems that do not have a heap or its expensive, for example real time microcontrollers and wasm.

**Comment by msprotz** [comment]
yes these functions are definitely staying, no plans to remove them in the near future -- headers were just consolidated when a lot more hash algorithms started landing

**Comment by aep** [comment]
great thanks

**Comment by aep** [comment]
hmm something has changed. Hacl_Hash_SHA2_update_last_256 now requires a "prev_len" argument. 

is setting that to zero correct?


this doesnt work:
```
u32  state[8];
Hacl_Hash_Core_SHA2_init_256(state);

u8  block[64];
Hacl_Hash_SHA2_update_256(state, block);

u8  block[64];
Hacl_Hash_SHA2_update_256(state, block);

u8  rest[10];
Hacl_Hash_SHA2_update_last_256(state, 0, rest, 10);

Hacl_Hash_Core_SHA2_finish_256
```

**Comment by msprotz** [comment]
@karthikbhargavan thoughts? we explicitly didn't document this API because it *is* error-prone, but maybe we should say a word or add a comment that shows up in the C code? the problem here is that the streaming API requires heap-allocation

@aep 
- prev_len is the amount of data you've previously fed into the hash function, in your case, 64 + 64 -- surely the previous API must have required a parameter along those lines? what was the signature of the update_last you were using, and from how long ago?
