### ISSUE TITLE
Allowed IV lengths for AES128 and AES256 CTR mode?

### ISSUE THREAD

**Issue by niekbouman** [project-everest/hacl-star#335]
What is the range of allowed IV lengths for AES CTR mode in EverCrypt_CTR.h ?

In v0.2.1, in the c source file (EverCrypt_CTR.c, line 138), I see an 'if'-statement that checks that the iv_len is at least 12 bytes.
However, in line 150 there is a calloc for 16 bytes.

Does that mean that for AES128 CTR mode the IV len range is 12 up to and including 16 bytes?
Same question for the AES256-variant.

kind regards,
Niek

**Comment by msprotz** [comment]
Hi Niek,

Thanks for the report. First, a disclaimer: as stated on https://hacl-star.github.io/EverCryptCTR.html, EverCrypt_CTR is a WIP API. If you are authoring something serious that intends to use it, please shoot us an email to let us know so that we can try to make it better :).

From what I remember, the 16 bytes thing is just a complication of the way AES is specified in the RFC, and it's a corner case where (very fuzzy recollections here) the IV overlaps with the block number, but for some reason the RFC still allows or at least specifies this case. **You should use 12 bytes in any case.**

IV reduction is not available for AES-CTR since it relies on GCM.

Hope this helps,

Jonathan

**Comment by msprotz** [comment]
@karthikbhargavan please chime in if my recollections are wrong

**Comment by niekbouman** [comment]
> You should use 12 bytes in any case.

Thanks! I will do that.
