### ISSUE TITLE
Possible overflow

### ISSUE THREAD

**Issue by achamayou** [project-everest/hacl-star#361]
CodeQL has picked up this issue in a number of places in our extracted code: https://github.com/microsoft/CCF/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster

In case the link doesn't work:

![image](https://user-images.githubusercontent.com/4016369/95126457-719ead00-074e-11eb-8884-782f096e75e4.png)

![image](https://user-images.githubusercontent.com/4016369/95126534-9430c600-074e-11eb-8217-b3c963610f7a.png)

We do not use the Frodo KEM, and it's not clear to me from context if this really can overflow if that's impossible because of some constraint somewhere, but it seemed worth reporting just in case. We're on 983baba407d2c91134ee270656a3d2c35683e1ff.

**Comment by beurdouche** [comment]
From a quick look, according to the definition of that function, there is a precondition that makes sure this never overflows.
https://github.com/project-everest/hacl-star/blob/983baba407d2c91134ee270656a3d2c35683e1ff/code/frodo/Hacl.Impl.Frodo.Sample.fst#L115

A second pair of eyes would be nice... : )

**Comment by msprotz** [comment]
This is a computation of the form `E * sizeof T`.

`E` is statically guaranteed in F* to not exceed `2^32 - 1`. So the warning is irrelevant, I think. (Amaury do you buy this?) Unless of course you're at the C/F* boundary, and you're calling an F* function from C, and the `n1` parameter is provided by the caller, in which case we expect the caller to be aware of those restrictions and not violate them, otherwise all bets are off.

The outer multiplication `E * sizeof T` does not overflow here because since `sizeof uint8 = 1`, we're good to go.

In the general case where `sizeof T > 1`, `KRML_CHECK_SIZE` guarantees that there will be no overflow using SIZE_MAX.

Happy to look into this into more detail if this still seems suspicious. I'm not foolish enough to pretend I can't be bitten by C's integer promotion rules.

**Comment by achamayou** [comment]
@msprotz that sounds entirely reasonable to me, I thought there would be a static guarantee but I wasn't sure where to look for it. So long as `2 * n1 * n2 -> E` is guaranteed not to overflow, I believe there is no problem. The warning is against the promotion to unsigned long that happens because of the multiplication with sizeof, which _may_ hide an overflow, but cannot here. So I will tag this as a false positive.

@msprotz @beurdouche thank you for taking the time to look into this!
