### ISSUE TITLE
Removing files that don't verify or aren't used from `code`

### ISSUE THREAD

**Issue by jkzinzindohoue** [project-everest/hacl-star#37]
- [x] Cleanup stale files

- [x] Split `code/experimental` into `code/attic` and `code/experimental`

- [x] Move production ready code from `code/experimental` to `code`

- [x] Move frozen primitives and experiments to `code/attic`, only keep in `code/experimental` primitives which will be shortly moved to `code`

**Comment by s-zanella** [comment]
Just created a `code/attic` directory and moved a few stale files in `code` there. I identified them by going through files in `code` (except `code/experimental`) that weren't verified during CI. 

- [Moved to `attic/bignum`] `code/bignum/Hacl.Bignum.Lemmas.fst`
- [Moved to `attic/hash`] `code/hash/Hacl.Hash.SHA2_256.PrePost.fst`
- [Moved to `attic/salsa-family`] `code/salsa-family/AEAD.Chacha20.fst`
- [Moved to `attic/salsa-family`] `code/salsa-family/Hacl.Spec.Symmetric.Chacha20.fst`
- [Moved to `attic/ed25519`] `code/ed25519/Hacl.BignumQ.fst`
- [Moved to `attic/ed25519`] `code/ed25519/Hacl.Impl.Ed25519.Ladder.BigLoop.fst`
- [Moved to `attic/api`] `code/api/Hacl.Hash.fst`
- [Removed, same as in `code/api`] `code/api/interfaces/Hacl.Constants.fst`
- [Moved to `attic/lib`] code/lib/Utils.fst
- [Moved to `attic/lib/kremlin`] `code/lib/kremlin/Hacl.SBuffer.fst`

I kept `code/api/Hacl.SecretBox.fst`, which looks stale and currently doesn't verify. It doesn't seem hard to fix.

I'm unsure about the role of `code/api/interfaces`. The `fsti` files in there don't seem to be used anywhere and, for instance, typechecking `code/api/Hacl.Box.fst` against `code/api/interfaces/Hacl.Box.fsti` fails.

I patched and added to CI some files meant to be verified that weren't, either because they regressed or were (un)intentionally omitted. Notably, the whole `code/lib` and `code/lib/kremlin` directories.

**Comment by beurdouche** [comment]
Directory `attic` was removed in the `dev` branch
