### ISSUE TITLE
Compilation failure on s390x

### ISSUE THREAD

**Issue by victor-dumitrescu** [project-everest/hacl-star#393]
We've gotten a report of `hacl-star-raw` failing to compile on s309x. The problem seems to be that `-mavx -mavx2` are being passed even though these options aren't available. @msprotz mentioned that this currently happens on any platform that we don't explicitly detect as not being x86, so maybe it would be worth changing that default?

Additionally, in this specific case, the reporter mentioned that vector intrinsics could still be used, but we'd need to bundle the [z intrinsics](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/s390/vecintrin.h) too and pass `-march=z13 -mzvector`.

CC @franziskuskiefer

**Comment by msprotz** [comment]
Thanks for the report Victor! Essentially my proposal is to:
- disable 128, 256 and inline assembly (like we currently do for x86) by default, UNLESS
- we find an armv8 chip that supports NEON OR we find an x64 chip

One thing we could improve is to change
```
-include Makefile.config
```
to
```
Makefile.config:
        ./configure
```
in the dist/gcc-compatible/Makefile so that people who are used to hitting "make" still get a decent version compiled

**Comment by franziskuskiefer** [comment]
>  Essentially my proposal is to ...

This is definitely the safer default and should avoid issues with less common/tested platforms.
We have all the mechanisms in place in `configure`  but don't use it for `avx`. We should resolve this TODO and make sure configure is called before the rest of the Makefile is processed.
https://github.com/project-everest/hacl-star/blob/3612beeaacf11bbaef7c0bba8b24e005924c2f1f/dist/Makefile.tmpl#L83-L85

**Comment by franziskuskiefer** [comment]
@victor-dumitrescu can you check if #406 solved this issue and close it after confirming?
