### ISSUE TITLE
Build error on certain s390x machines

### ISSUE THREAD

**Issue by victor-dumitrescu** [project-everest/hacl-star#511]
The `configure` script currently passes the following compilation flags for `*_128.c` files on s390x: `-m64 -mzarch -mvx -mzvector -march=z15"`. The `-march=z15` flag causes compilation to fail on older machines (e.g. z14).

The solution seems to be passing `-march=native` instead, but I'm opening this issue in case there are any objections / alternative solutions.

CC @Kachoc @msprotz

**Comment by Kachoc** [comment]
We implemented support for IBMz following IBM's demand. From what I remember we used `-march=z15` because we wanted the best performance (even though I don't think this should have any impact), some of the intrinsics we use only work on some recent configs, and IBM only needed support for z15. Following this, I'm ok with changing this to `-march=native`.

**Comment by victor-dumitrescu** [comment]
The change from `z15` to `native` was made in #518.

Closing for now, but might need to revise this choice later depending on priorities.
