### ISSUE TITLE
gcc-compatible no longer compiles for mips

### ISSUE THREAD

**Issue by aep** [project-everest/hacl-star#524]
i'm upgrading from a very old clone before ./configure existed and gcc-compatible was just portable C
at least it's unclear how to compile it now

./configure just fails with incorrect gcc params

```
cc1: error: unrecognized argument in option '-march=native'
```

and creating an empty config.h (since we don't have any of those x86 intrinstics on mips) fails to compile because there is no implementation of libintvector

```
3rdparty/hacl-star/dist/gcc-compatible/Hacl_Poly1305_256.h:44:9: error: unknown type name ‘Lib_IntVector_Intrinsics_vec256’
```

**Comment by msprotz** [comment]
Here's a sample of a hand-written config.h:

https://github.com/project-everest/hacl-star/blob/master/dist/mozilla/config.h

I suggest you define all of these to 0 and see if it compiles that way, entirely bypassing the configure script?

In the meanwhile you are correct that the configure script ought to be fixed. Thanks for the report.

**Comment by aep** [comment]
no, there's no portable implementation of intvector, so this won't work.
i've been informed off-list that this is a commercial feature anyway. 

unfortunately in that case hacl has no benefit over other non-portable cryptolibs and we'll be migrating away.

**Comment by beurdouche** [comment]
The commercial or not-commercial features are unrelated to this project and repository.

**Comment by aep** [comment]
there's some mixes messages here. 

Either way if the technical decision is to require porting effort for each cpu, this is not the correct project for our use case. 
We can leave this open if you want to of course, but i personally would not recommend even attempting "a mips port" Mips is actually at least 8 different cpu architectures with subtle bugs in subrevisions, most of which are dead.

**Comment by beurdouche** [comment]
@aep Let me clarify the confusion here... : ) **the HACL* project and this repository are not related to any commercial project.**
Everything in this project is open source and under very permissive licenses so that everyone can use it and contribute to this project.

If for example you have a feature request, it should be sent either to the maintainers mailing list or like you did through opening an issue. Now, if the authors don't have the ability or resources to add that feature, you might find a third party to develop that feature and contribute it back to this repository (under the condition of course that the core team is willing to accept it). We might advertise one of those third party in the future, but any third party could do this.

If you don't mind, I'd like to know which of the HACL* authors you reached out to and who actually answered you that adding supporting MIPS is a commercial feature, so that I can make sure this doesn't happen again... : ) 

Feel free to close this issue if you don't need this anymore.
Best,
Benjamin

**Comment by franziskuskiefer** [comment]
It is no secret that Cryspen offers commercial support for HACL for anyone interested in long-term support of the project.
If a someone is using MIPS and wants to use HACL, they can rely on open source contributors to add support or they contract Cryspen to do so.

**Comment by aep** [comment]
thanks @beurdouche .  this is perfectly reasonable and i don't feel like ratting them out, especially since they clearly did it in good faith.

It's just not viable for us. We might have chipped in for features, but the amount of work required to have a custom cpu port for each mips variant is unobtainable for our small shop.

**Comment by beurdouche** [comment]
> It is no secret that Cryspen offers commercial support for HACL for anyone interested in long-term support of the project. If a someone is using MIPS and wants to use HACL, they can rely on open source contributors to add support or they contract Cryspen to do so.

Cryspen affairs must keep out of the this repository. Thank you!

**Comment by Frosne** [comment]
I agree with Ben. I believe that HACL* should stay open-source.

**Comment by msprotz** [comment]
@aep : Just to clarify your remark about "custom CPU ports". There is no need to write MIPS-specific code to make HACL* work on MIPS. Most of HACL* is portable C, except for the _128 and _256 files which rely on compiler intrinsics. The fact that HACL* does not currently compile on MIPS is purely a build system issue.

Here's the reason. Normally, the `configure` script takes care of disabling 128/256 files if it appears there is no support for 128/256 variants for your target architecture. Unfortunately, the `configure` script is broken in your scenario and cannot write a proper Makefile.config.

You could attempt to fix this easily by editing the configure script (it's hand-written bash) and removing the two instances of `-march=native` at lines 117 and 118. That may or may not be enough.

Writing custom MIPS-specific support for vectorized and/or optimized implementations is another matter.
